### PR TITLE
added 'checkClusters'

### PR DESCRIPTION
**Pull request by jkbhagatio**

### CODE REVIEW

**Comment by rossant** [comment]
Thanks. Have you tested it on a dataset and tried to open it in phy? Shouldn't we also renumber the spike templates in st3

**Comment by jkbhagatio** [comment]
Yes, ran it on a dataset to see both cases (when there are empty clusters, and when there aren't), but didn't try to open the saved output in phy. Will check that now. And yes, good point about spike templates in `st3`, will add that to this PR

**Comment by jkbhagatio** [comment]
> Have you tested it on a dataset and tried to open it in phy? 

yup, looks good to me.

> Shouldn't we also renumber the spike templates in st3.

done this with latest commit. there may be a better way than what I've done? If so, mind just fixing this up and tagging me in a comment so I can see what you do? Thanks!

**Comment by kushbanga** [comment]
Empty clusters get formed during the merging phase, if you modify ```find_merges``` to run your function at the end does this solve the issue?

**Comment by jkbhagatio** [comment]
oh thanks @kushbanga for the info on where the empty clusters are happening. I thought this `checkClusters` function I've created could be potentially extended in the future in case there are other bugs we notice and we want to check for at the end of the sorting. @rossant what do you think?

**Pull request merged**
